version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
    networks:
      - localstack_network
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack_network
  bootcamp-backend:
    image: gustavolucen4/bootcamp-backend:latest
    container_name: bootcamp-backend
    ports:
      - 8082:8082
    depends_on:
      - mongodb
      - localstack
    networks:
      - localstack_network
networks:
  localstack_network: